### ISSUE TITLE
can't start the bot

### ISSUE THREAD

**Issue by bktfjr** [0xfinder/topgg-autovoter#2]
i installed everything on requirements python,selenium also chrome driver and remove examples from tokens and add tokens , but when i press multivote nothing happens , there is error

**Comment by Hopefuls** [comment]
Sounds like a skill issue

**Comment by bktfjr** [comment]
> Sounds like a skill issue

is it working with you ? if you would like to help me i would be grateful

**Comment by 0xfinder** [comment]
Can you state your error?

**Comment by 0xfinder** [comment]
Hey, I just pushed out a fix, please install again and let me know if it works

**Comment by bktfjr** [comment]
Testing , it works fine for now 🙃
Thanks my friend 🙂
