### ISSUE TITLE
How do I add to path?

### ISSUE THREAD

**Issue by kogechaa** [0xfinder/topgg-autovoter#4]
I don't really know where and how to add a path for the chromedriver. If anyone can help thank you

**Comment by 0xfinder** [comment]
Could you try without adding to PATH and see if it works? If not, to add to PATH, (I'm assuming you're on windows), download the chrome driver and copy the directory where the .exe file is in, then go to system variables, and edit the Path field under User or System, then create a new environment variable and paste the directory there.

[Guide](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/)

**Comment by kogechaa** [comment]
Thank you!
