### ISSUE TITLE
I got an error while using this script

### ISSUE THREAD

**Issue by Hopeful2x2** [0xfinder/topgg-autovoter#5]
loginElem = WebDriverWait(browser, 10).until(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x003869A3+2582947]
        Ordinal0 [0x0031A6D1+2139857]
        Ordinal0 [0x00213A98+1063576]
        Ordinal0 [0x0023FF3E+1244990]
        Ordinal0 [0x0024013B+1245499]
        Ordinal0 [0x00269F52+1417042]
        Ordinal0 [0x00258594+1344916]
        Ordinal0 [0x0026834A+1409866]
        Ordinal0 [0x00258366+1344358]
        Ordinal0 [0x00235176+1200502]
        Ordinal0 [0x00236066+1204326]
        GetHandleVerifier [0x0052BE02+1675858]
        GetHandleVerifier [0x005E036C+2414524]
        GetHandleVerifier [0x0041BB01+560977]
        GetHandleVerifier [0x0041A8D3+556323]
        Ordinal0 [0x0032020E+2163214]
        Ordinal0 [0x00325078+2183288]
        Ordinal0 [0x003251C0+2183616]
        Ordinal0 [0x0032EE1C+2223644]
        BaseThreadInitThunk [0x7703FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77757A9E+286]
        RtlGetAppContainerNamedObjectPath [0x77757A6E+238]

**Comment by 0xfinder** [comment]
Just pushed a fix, let me know if it works

**Comment by Hopeful2x2** [comment]
It works fine now <3. Thank u
